Notification
otabeksherman/project-management-server pull request #14
Opened 2022-12-22 08:50 UTC by talbenzur

2022-12-23 00:42 UTC, otabeksherman requested changes

2022-12-24 16:04 UTC, rachelgitovich commented on src/main/java/projectManagement/util/MailUtil.java
> +                .getResourceAsStream("/client_secret_832098226915-qg699ff2itjs5q3hlifomniigbf3jhpv.apps.googleusercontent.com.json")));
You can just rename the file to "credentials.json"

2022-12-25 10:17 UTC, otabeksherman approved these changes
Looks good

2022-12-25 10:20 UTC, rachelgitovich commented on src/main/java/projectManagement/entities/user/User.java
> +    @JsonIgnore
move jsonignore to board and remove it here

2022-12-25 10:30 UTC, merged