Raw generic use
otabeksherman/project-management-server pull request #28
Opened 2022-12-28 20:56 UTC by talbenzur

2022-12-28 23:06 UTC, rachelgitovich commented on src/main/java/projectManagement/controller/BoardController.java
> +    public ResponseEntity<BaseResponse<Long>> getBoard(@PathVariable Long id,
why did you change it to long? it should be board

2022-12-28 23:08 UTC, rachelgitovich commented on src/main/java/projectManagement/controller/BoardController.java
> +    public ResponseEntity<BaseResponse<String>> share(@RequestAttribute ShareBoardDto dto, @RequestAttribute String userEmail) {
here also, returned objects should remain as they were

2022-12-28 23:14 UTC, rachelgitovich requested changes
The returned objects should remain as they were

2022-12-29 05:24 UTC, talbenzur commented on src/main/java/projectManagement/controller/BoardController.java
> +    public ResponseEntity<BaseResponse<Long>> getBoard(@PathVariable Long id,
the objectthat we return is id- Long. 
its ok i didn't change the object that we return

2022-12-29 05:25 UTC, talbenzur commented on src/main/java/projectManagement/controller/BoardController.java
> +    public ResponseEntity<BaseResponse<String>> share(@RequestAttribute ShareBoardDto dto, @RequestAttribute String userEmail) {
also, we return the userEmail which is String

2022-12-29 11:08 UTC, rachelgitovich approved these changes

2022-12-29 11:35 UTC, merged